name: validate

on: [push]

jobs:

  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade poetry
        poetry install --with dev
    - name: pylint
      run: |
        poetry run pylint --fail-under 9.5 ./

  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade poetry
        poetry install --with dev
    - name: black
      run: |
        poetry run black ./

  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade poetry
        poetry install --with dev
    - name: unittest
      run: |
        poetry run python3 -m unittest

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade poetry
        poetry install --with dev
    - name: coverage
      run: |
        poetry run coverage run --source . -m unittest
        poetry run coverage report -m --fail-under 80
